import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ weight: ["400", "500"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CatWiki",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`relative ${montserrat.className}`}>{children}</body>
    </html>
  );
}
